# Generated by Django 3.1.4 on 2020-12-14 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0004_auto_20201214_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapysession',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='therapysession',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
