# Generated by Django 3.1.4 on 2020-12-17 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0006_therapist_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='therapist',
            name='avatar',
        ),
    ]
