# Generated by Django 3.1.4 on 2020-12-20 00:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0007_remove_therapist_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapysession',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='therapysession',
            name='surrogate',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
    ]
