# Generated by Django 3.1.4 on 2020-12-20 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0008_auto_20201220_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapysession',
            name='status',
            field=models.CharField(choices=[('AC', 'Approved'), ('RJ', 'Rejected'), ('PD', 'Pending')], default='PD', max_length=2),
        ),
    ]
