# Generated by Django 3.1.4 on 2020-12-21 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0009_therapysession_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapist',
            name='address',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='therapist',
            name='license',
            field=models.FileField(blank=True, null=True, upload_to='licenses/'),
        ),
        migrations.AddField(
            model_name='therapist',
            name='office_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='therapist',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='therapist',
            name='status',
            field=models.CharField(choices=[('AC', 'Active'), ('IN', 'Inactive')], default='IN', max_length=2),
        ),
    ]
