# Generated by Django 3.1.4 on 2020-12-22 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0011_availabletimerange'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='therapysession',
            name='approved',
        ),
    ]
