# Generated by Django 3.1.4 on 2020-12-28 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0015_auto_20201226_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapysession',
            name='status',
            field=models.CharField(choices=[('AC', 'Approved'), ('RJ', 'Rejected'), ('PD', 'Pending'), ('PC', 'Payment completed')], default='PD', max_length=2),
        ),
    ]
