# Generated by Django 3.1.4 on 2020-12-13 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201211_0106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_coach',
            new_name='is_therapist',
        ),
    ]
