# Generated by Django 3.1.4 on 2020-12-14 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201213_0030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_therapist',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_therapist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default='', max_length=60),
        ),
    ]
