# Generated by Django 3.1.4 on 2020-12-16 04:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20201216_0320'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='surrogate',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
    ]
