# Generated by Django 3.1.4 on 2020-12-16 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_surrogate'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
