# Generated by Django 3.1.4 on 2020-12-28 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='charges_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
