# Generated by Django 3.1.4 on 2021-02-27 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20210227_2149'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('user', 'therapist'), name='unique_user_review'),
        ),
    ]
