# Generated by Django 3.1.4 on 2021-02-27 23:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20210227_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='surrogate',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
